_format_version: "2.1"

services:
  - name: service1
    url: http://service1:3010/users
    routes:
    - name: service1
      paths:
      - /service1

#  - name: service2
#      url: http://localhost:3020/users
#      routes:
#      - name: service2
#      paths:
#      - /service2
